language: generic
sudo: required #need sudo to build
services:
  - docker #travis will install a copy of docker
  
before_install: #series of command executed before our tests 
  - docker build -t justinlblc/docker-react -f Dockerfile.dev . #we build our container and tag it to easily refer to it in the future

script: #supposed to contain the commands to run the tests
  - docker run -e CI=true justinlblc/docker-react npm run test #nm run tests sends us to a menu, so to exit after the first test, we had -e CI=true

deploy: #add a config to tell Travis how to take our app and deploy it to AWS
  provider: elasticbeanstalk
  region: "us-east-2"        #Depends upon where we created our elasticbeanstalk instance. Look at the URL, it says us-east-2
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-586516611809"        #bucket in which Travis CI will put our files into. Look in services, S3, you have the name.
  bucket_path: "docker-react"                                   #app name by default
  on:
    branch: master      #any time we push code on branch master, it is time to deploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"